use_frameworks!

platform :ios, '14.0' 

target 'MLYSDK_Example' do
  pod 'MLYSDK', :path => '../' 
  pod 'GCDWebServer', '~> 3.5.4'
  pod 'Mux-Stats-AVPlayer', '~> 3.1.0'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.31.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
